server:
  port: 8888

spring:
    profiles:
      active: native
    application:
      name: msvc-server
    main:
      web-application-type: reactive
    cloud:
      config:
        server:
          native:
            search-locations: classpath:/configurations